# Generated by Django 3.1.4 on 2020-12-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201211_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/default_profile_400x400.png', upload_to='email/%Y-%m'),
        ),
    ]
