# Generated by Django 3.1.4 on 2020-12-28 01:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201211_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/default_profile_400x400.png', upload_to=user.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=user.models.get_UUID, max_length=50, unique=True),
        ),
    ]
